[package]
name = "rusttt"
version = "0.0.1"
authors = ["Matthew Gianni"]
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.29"
rand = "0.9.2"
